[build]
  functions = "functions"
  command = "npm install"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "mongodb"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
